### ISSUE TITLE
Could I have your trained model?

### ISSUE THREAD

**Issue by wy-luke** [leehe228/LogisticsEnv#4]
Excuse me, may I respectfully ask if it would be possible for you to share your trained model `model.pt` files with me?  My computer's performance is not quite good.

I would be extremely grateful for your help. Thanks! And your paper is awesome!

**Comment by leehe228** [comment]
Hello.

Excuse me for not having answered your letter sooner. 
I am currently serving in the Air Force according to the Korean military law.

I will look for the learning model file and reply to you again.

Thank you.

**Comment by wy-luke** [comment]
@leehe228 Thank you so much!!!

**Comment by leehe228** [comment]
I am so sorry for late response, because of serving for army.

https://konkukackr-my.sharepoint.com/:f:/g/personal/leehe228_konkuk_ac_kr/Eu7uH-dz3EtIuC8j-l6uxP8B3ktO6UiMUeMPrw7QXMWHIg?e=zlP0gX

This is a link for 30k-epoch-trained MAAC model log file.

I also have other trained files but they are crashed. So I am training model again now.
I will notice you when a training is done. Thank you so much.

**Comment by wy-luke** [comment]
@leehe228 Thank you so so so so so so so so much!!!

**Comment by manaspalaparthi** [comment]
@leehe228 by any chance you have the 150k episode MAAC model? i want to compare the results with my model.

**Comment by leehe228** [comment]
@manaspalaparthi Hello, I am sorry for the late reply. There is a problem with the GPU server that we are currently using, so we are learning again after initialization. After that, we plan to provide the learned model data and results again. We will provide you with the results as soon as possible. Sorry for not being able to help you right away.

**Comment by yyjdsads** [comment]
https://konkukackr-my.sharepoint.com/:f:/g/personal/leehe228_konkuk_ac_kr/Eu7uH-dz3EtIuC8j-l6uxP8B3ktO6UiMUeMPrw7QXMWHIg?e=zlP0gX    This link is invalid, can you give a new link?

**Comment by yyjdsads** [comment]
> @leehe228 Thank you so much!!!
Have you saved this file? I can't open it now, can you share it?

**Comment by leehe228** [comment]
I apologise for the confusion, but I've had an issue with my lab server and are currently re-starting learning. I will have the files available within a week, thank you for your patience.

**Comment by leehe228** [comment]
@yyjdsads 

Here is the link. You can download trained model files (.pth) Thank you for your patience!
https://drive.google.com/drive/folders/1cd17nqOY6nNDjxIUsFIw1KQF8No4MgIV?usp=share_link
