### ISSUE TITLE
Question about Logistics.x86_64 in Build_Linux

### ISSUE THREAD

**Issue by XZhang878** [leehe228/LogisticsEnv#6]
Sorry to bother you, when I reproduced your code, the error： mlagents_envs.exception.UnityEnvironmentException: Environment shut down with return code 1. During my search for errors, I found that when the Logistics.x86_64 file was automatically generated , this error will disappear. Please tell me how to generate your Logistics.x86_64 file.

**Comment by leehe228** [comment]
@XZhang878 Hello, I am so sorry for the late reply. LogisticsEnv build file can be built using 2020.3.13f1 version of Unity. (supports Universal Build such as Mac, Windows, Ubuntu, etc.) Currently, I have a problem with the GPU server I was using, so I plan to deploy the release various version of built environment files for various OS after reset the server. Thank you for your interest and if you have any problems with the environment file I will provide soon, please let me know. Thank you.

**Comment by leehe228** [comment]
Thank you for your patience. I've just published a new build to this repository README.md with a link to download the build release. If you have any issues, please let us know. Thank you.
