### ISSUE TITLE
Build for windows

### ISSUE THREAD

**Issue by WajidIqbal33** [leehe228/LogisticsEnv#8]
Hello Sir,
I am trying to run your code on windows, can you please help which path I shall give for Build_windows. I am totally lost, thanks

**Comment by leehe228** [comment]
Thank you for your long wait. I have posted a link to download the Build Release in the README.md of this repository. If you have any issues, please let us know. Thank you.

**Comment by 04-jj** [comment]
> Hello Sir, I am trying to run your code on windows, can you please help which path I shall give for Build_windows. I am totally lost, thanks

Hello Sir, can you try it successfully on windows? thanks
